[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Changing size of booster packs
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
elseif self.name == 'Amber Acorn' and not reset and #G.jokers.cards > 0 then
    G.jokers:unhighlight_all()
    for k, v in ipairs(G.jokers.cards) do
        v:flip()
    end
    if #G.jokers.cards > 1 then 
        G.E_MANAGER:add_event(Event({ trigger = 'after', delay = 0.2, func = function() 
            G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 0.85);return true end })) 
            delay(0.15)
            G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 1.15);return true end })) 
            delay(0.15)
            G.E_MANAGER:add_event(Event({ func = function() G.jokers:shuffle('aajk'); play_sound('cardSlide1', 1);return true end })) 
            delay(0.5)
        return true end })) 
    end
end
'''
position = "after"
payload = '''
if G.GAME.used_vouchers['v_mksn_cloak'] and G.GAME.blind.boss and not reset then
    ease_hands_played(1)
end
'''
match_indent = true
times = 1