[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

    # Reduce blind size
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
if blind and blind.name then
    self:change_colour()
else
    self:change_colour(G.C.BLACK)
end
'''
position = "after"
payload = '''
if G.GAME.used_vouchers['v_mksn_dagger'] then
    self.mult = self.mult*0.8
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if G.GAME.used_vouchers['v_mksn_dagger'] then
    blind_amt = blind_amt*0.8
end
'''
match_indent = true
times = 1